version: '3'

services:
  php:    
    build:
      context: ./vm/php
      dockerfile: Dockerfile
    image: php7.4-fpm-custom
    container_name: ${APP_NAME}-php
    restart: unless-stopped
    volumes:
      - ./vm/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./app:/var/www

  webserver:
    image: nginx
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    depends_on: 
      - php
    ports:
      - 8000:80
      - 443:443
    volumes:
      - ./vm/nginx/:/etc/nginx/conf.d/
      - ./app:/var/www

  adminer:
    image: adminer
    container_name: ${APP_NAME}-adminer
    restart: unless-stopped
    depends_on: 
      - db
    ports: 
      - 8080:8080
  
  db:
    image: mariadb
    container_name: ${APP_NAME}-mariadb
    restart: unless-stopped
    environment:
      SERVICE_NAME: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: Asia/Manila
    volumes:
      - ./vm/mariadb/my.cnf:/etc/mysql/my.cnf
      - ./db:/var/lib/mysql